version: '3.7'
services:
  server:
    container_name: app
    build:
      context: api/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./api/app:/app/server
      - ./api/requirements.txt:/app/requirements.txt
      - ./venv:/app/venv
    ports:
      - 8000:8000
    env_file: ./api/.env
    environment:
      TZ: Asia/Seoul
    restart: always
    depends_on:
      - db
    
  db:
    container_name: db
    build:
      context: db/
      dockerfile: Dockerfile    
    ports:
      - 3306:3306
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/dbconf/conf.d:/etc/mysql/conf.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Seoul
