version: "3.3"
services:
  server:
    container_name: 'fastapi-crud-starter-app'
    build:
      context: ./api
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./api/app:/app/server
      - ./api/requirements.txt:/app/requirements.txt
      - ./venv:/app/venv
    ports:
      - "8000:8000"
    env_file: ./api/.env
    environment:
      TZ: "Asia/Seoul"
    restart: always
    depends_on:
      - db
    
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: 'fastapi-crud-starter-db'
    ports:
      - "3306:3306"
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/dbconf/conf.d:/etc/mysql/conf.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Asia/Seoul"
